include_patterns:
  - "**/*.go"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.env"
  - "**/*.sh"
  - "**/*.bat"
  - "**/*.ps1"
  - "**/*.ts"
  - "**/*.js"
  - "**/*.html"
  - "**/*.css"

exclude_patterns:
  - "**/.*"
  - "**/node_modules"
  - "**/dist"
  - "**/.git"
  - "**/__pycache__"
  - "**/bin"
  - "**/*.exe"