#!/bin/sh
set -e

# === WebUI Docker Entrypoint ===
# 1. Генерирует nginx.conf из шаблона с envsubst
# 2. Генерирует js/modules/config.js с рантайм параметрами API
# 3. Запускает nginx

NGINX_TEMPLATE="/etc/nginx/conf.d/default.conf.template"
NGINX_CONF="/etc/nginx/conf.d/default.conf"

# Параметры по умолчанию
: "${NGINX_PORT:=80}"
: "${API_HOST:=loadbalancer}"
: "${API_PORT:=18081}"
: "${LB_PORT:=18080}"
: "${CPPWORKER_HOST:=cppworker-cpu}"
: "${CPPWORKER_PORT:=18091}"
: "${API_TOKEN:=}"
: "${REFRESH_INTERVAL:=5000}"
: "${MAX_RECONNECT_ATTEMPTS:=10}"
: "${RECONNECT_INTERVAL_BASE:=3000}"

# 1. Генерация nginx.conf
echo "[entrypoint] Generating nginx config..."
awk '{
    gsub(/\$\{NGINX_PORT\}/, "'"$NGINX_PORT"'");
    gsub(/\$\{API_HOST\}/, "'"$API_HOST"'");
    gsub(/\$\{API_PORT\}/, "'"$API_PORT"'");
    gsub(/\$\{LB_PORT\}/, "'"$LB_PORT"'");
    gsub(/\$\{CPPWORKER_HOST\}/, "'"$CPPWORKER_HOST"'");
    gsub(/\$\{CPPWORKER_PORT\}/, "'"$CPPWORKER_PORT"'");
    print
}' "$NGINX_TEMPLATE" > "$NGINX_CONF"

# 2. Генерация config.js для рантайм параметров
CONFIG_JS="/usr/share/nginx/html/js/modules/config.js"

cat > "$CONFIG_JS" <<EOF
/**
 * Runtime WebUI config — generated by entrypoint.sh
 */
window.WEBUI_CONFIG = window.WEBUI_CONFIG || {};
Object.assign(window.WEBUI_CONFIG, {
    // API endpoint (relative или абсолютный URL)
    API_BASE: '',
    // WebSocket endpoint
    WS_URL: null,
    // API токен для аутентификации
    API_TOKEN: '${API_TOKEN}',
    // cppworker URL (через nginx proxy)
    CPPWORKER_URL: '/api/worker',
    // Интервал обновления данных (мс)
    REFRESH_INTERVAL: ${REFRESH_INTERVAL},
    // WebSocket reconnect
    MAX_RECONNECT_ATTEMPTS: ${MAX_RECONNECT_ATTEMPTS},
    RECONNECT_INTERVAL_BASE: ${RECONNECT_INTERVAL_BASE}
});
EOF

echo "[entrypoint] Config generated:"
echo "  NGINX_PORT=$NGINX_PORT"
echo "  API_HOST=$API_HOST"
echo "  API_PORT=$API_PORT"
echo "  CPPWORKER_HOST=$CPPWORKER_HOST"
echo "  CPPWORKER_PORT=$CPPWORKER_PORT"
echo "  API_TOKEN=${API_TOKEN:+(set)}"
echo "  REFRESH_INTERVAL=$REFRESH_INTERVAL"

# 3. Запуск nginx (передаём аргументы CMD)
exec "$@"